# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/semiotic

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install

      - run:
          name: tests
          command: |
            npm run test -- --maxWorkers=2 --cacheDirectory=~/.jestcache

      - run:
          name: tests against the dist copy (for the web)
          command: |
            npm run test:dist

      - save_cache:
          paths:
            - ~/.npm
            - ./node_modules
            - ~/.jestcache
          key: v2-dependencies-{{ checksum "package.json" }}

      # store the screenshots for access on Circle CI
      - store_artifacts:
          path: screenshots
          destination: screenshots
